# MongoDB authentication elements

[MongoDB]
mongo_username = "pdemaers"
mongo_password= "nKZmkEt4BI5PGolE"
mongo_cluster_url = "cluster0.lzhjxqo.mongodb.net"
DATABASE_NAME = "personal"
COLLECTION_NAME = "kb_ledenlijst"

# Autorized users

[Users]
usernames = ["admin", "bestuur"]
names = ["Administrator", "Bestuur"]
passwords = ["KB_ledeN123", "KB_leDen123"]

# Google app passwords

[app_key]
email_app_key = "hdlp xdlp htnw tzkd"